"""empty message

Revision ID: 4fd555443891
Revises: f929b673c253
Create Date: 2021-07-29 13:33:06.616718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd555443891'
down_revision = 'f929b673c253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pic_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pic_ratings_rating'), 'pic_ratings', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pic_ratings_rating'), table_name='pic_ratings')
    op.drop_table('pic_ratings')
    # ### end Alembic commands ###
